---
title: "NN_list_sym"
author: "Trevor Tivey"
date: "2/20/2019"
output: html_document
---

```{r, libraries, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
#setwd("/local/path/to/data")
set.seed(123)

#libraries

library(data.table)
library(ggplot2)
library(spatstat)
library(plyr)
library(dplyr)


```

## create lists

```{r, apo lists, echo = FALSE}

# Set directory to folder containing x,y,z coordinates of cell populations
setwd("./input sym")

  # Create subset lists that are organized in corresponding order to each other
  # Files containing object coordinates of all symbiont cluster centers of mass (autofluorescence)
  s_symlist = list.files(pattern = "C1-")
  s_symlist
  # Files containing object coordinates of host EdU-labeled nuclei
  s_edulist = list.files(pattern = " [1-3].txt")
  s_edulist
  # Files containing object coordinates of host nuclei (Hoechst labeled)
  s_nuclist = list.files(pattern = "C4-")
  s_nuclist

```

## Loop for apos

You can also embed plots, for example:

```{r, apo for loop, echo=FALSE}

# Loop to find k=1-12 nearest neighbors between symbionts and edu, symbionts and nuclei, and edu and nuclei
#loop to find k=12 nearest neighbors between symbionts and edu, symbionts and nuclei, and edu and nuclei
for(i in 1:length(s_edulist)) {
  
  setwd("./input sym")
  
  s_edu <- read.csv(s_edulist[i], header = T, sep = "\t")
  s_symbionts <- read.csv(s_symlist[i], header = T, sep = "\t")
  s_nuclei <- read.csv(s_nuclist[i], header = T, sep = "\t")
  
  s_filenmEN <- sub("txt", "csv", s_edulist)
  print(s_filenmEN[i])
  s_filenmES <- sub("txt", "csv", s_symlist)
  print(s_filenmES[i])
  s_filenmNS <- sub("txt", "csv", s_nuclist)
  print(s_filenmNS[i])
  
  s_nucleix <- range(s_nuclei[,11])
  s_nucleiy <- range(s_nuclei[,12])
  s_nucleiz <- range(s_nuclei[,13])
  s_pnuclei <- ppp(s_nuclei[,11], s_nuclei[,12], s_nucleix, s_nucleiy)
  s_pnuclei3 <- pp3(s_nuclei[,11], s_nuclei[,12], s_nuclei[,13], s_nucleix, s_nucleiy, s_nucleiz)
  
  s_symbiontsx <- range(s_symbionts[,12])
  s_symbiontsy <- range(s_symbionts[,13])
  s_symbiontsz <- range(s_symbionts[,14])
  s_psymbionts <- ppp(s_symbionts[,12], s_symbionts[,13], s_nucleix, s_nucleiy)
  s_psymbionts3 <- pp3(s_symbionts[,12], s_symbionts[,13], s_symbionts[,14], s_nucleix, s_nucleiy, s_nucleiz)
  
  s_edux <- range(s_edu[,12])
  s_eduy <- range(s_edu[,13])
  s_eduz <- range(s_edu[,14])
  s_pedu <- ppp(s_edu[,12], s_edu[,13], s_nucleix, s_nucleiy)
  s_pedu3 <- pp3(s_edu[,12], s_edu[,13], s_edu[,14], s_nucleix, s_nucleiy, s_nucleiz)
  
  s_edunuclei <- nncross(s_pedu3, s_pnuclei3, k=1:12)
  s_edusym <- nncross(s_pedu3, s_psymbionts3, k=1:12)
  s_nucsym <- nncross(s_pnuclei3, s_psymbionts3, k=1:12)
  s_nucleiedu <- nncross(s_pnuclei3, s_pedu3, k=1:12)
  s_symedu <- nncross(s_psymbionts3, s_pedu3, k=1:12)
  s_symnuc <- nncross(s_psymbionts3, s_pnuclei3, k=1:12)
  
  s_edunuclei2D <- nncross(s_pedu, s_pnuclei, k=1:12)
  s_edusym2D <- nncross(s_pedu, s_psymbionts, k=1:12)
  s_nucsym2D <- nncross(s_pnuclei, s_psymbionts, k=1:12)
  s_nucleiedu2D <- nncross(s_pnuclei, s_pedu, k=1:12)
  s_symedu2D <- nncross(s_psymbionts, s_pedu, k=1:12)
  s_symnuc2D <- nncross(s_psymbionts, s_pnuclei, k=1:12)
  
  setwd("../output sym/3d nn test")
  
  write.csv(s_edunuclei, s_filenmEN[i])
  write.csv(s_edusym, s_filenmES[i])
  write.csv(s_nucsym, s_filenmNS[i])
  
  setwd("../3d nn test reverse")
  
  write.csv(s_nucleiedu, s_filenmEN[i])
  write.csv(s_symedu, s_filenmES[i])
  write.csv(s_symnuc, s_filenmNS[i])
  
  setwd("../2d nn test")
  
  write.csv(s_edunuclei2D, s_filenmEN[i])
  write.csv(s_edusym2D, s_filenmES[i])
  write.csv(s_nucsym2D, s_filenmNS[i])
  
  setwd("../2d nn test reverse")
  
  write.csv(s_nucleiedu2D, s_filenmEN[i])
  write.csv(s_symedu2D, s_filenmES[i])
  write.csv(s_symnuc2D, s_filenmNS[i])
  
  setwd("../..")

}

```

